In [1]:
import torch
print(f'PyTorch version: {torch.__version__}')

PyTorch version: 2.9.1


# Using nn.Embedding

In [2]:
idx=torch.tensor([2,3,1])
num_idx=max(idx)+1
out_dim=5
embedding=torch.nn.Embedding(num_idx,out_dim)
embedding.weight

Parameter containing:
tensor([[-2.2696,  0.1663,  0.1873,  0.9324,  1.2489],
        [ 1.3342, -1.3869, -0.6273, -0.0880, -1.0567],
        [ 0.7265,  1.5293,  0.1368, -0.5554,  0.0078],
        [ 2.1502, -0.9243, -0.8262,  0.8574,  0.4048]], requires_grad=True)

In [3]:
embedding(torch.tensor([1]))

tensor([[ 1.3342, -1.3869, -0.6273, -0.0880, -1.0567]],
       grad_fn=<EmbeddingBackward0>)

In [4]:
embedding(torch.tensor([2]))

tensor([[ 0.7265,  1.5293,  0.1368, -0.5554,  0.0078]],
       grad_fn=<EmbeddingBackward0>)

In [5]:
idx=torch.tensor([2,3,1])
embedding(idx)

tensor([[ 0.7265,  1.5293,  0.1368, -0.5554,  0.0078],
        [ 2.1502, -0.9243, -0.8262,  0.8574,  0.4048],
        [ 1.3342, -1.3869, -0.6273, -0.0880, -1.0567]],
       grad_fn=<EmbeddingBackward0>)

# Using nn.Linear

In [6]:
onehot=torch.nn.functional.one_hot(idx)
onehot

tensor([[0, 0, 1, 0],
        [0, 0, 0, 1],
        [0, 1, 0, 0]])

In [7]:
linear=torch.nn.Linear(num_idx,out_dim,bias=False)
linear.weight

Parameter containing:
tensor([[ 0.2058, -0.3827,  0.2508,  0.0791],
        [ 0.3785,  0.3506,  0.2034,  0.2270],
        [ 0.2850,  0.0772,  0.4836,  0.1415],
        [-0.3663,  0.4264,  0.3722, -0.4460],
        [ 0.3471,  0.0060,  0.3057,  0.2609]], requires_grad=True)

In [8]:
linear.weight=torch.nn.Parameter(embedding.weight.T)
linear(onehot.float())

tensor([[ 0.7265,  1.5293,  0.1368, -0.5554,  0.0078],
        [ 2.1502, -0.9243, -0.8262,  0.8574,  0.4048],
        [ 1.3342, -1.3869, -0.6273, -0.0880, -1.0567]], grad_fn=<MmBackward0>)

In [9]:
embedding(idx)

tensor([[ 0.7265,  1.5293,  0.1368, -0.5554,  0.0078],
        [ 2.1502, -0.9243, -0.8262,  0.8574,  0.4048],
        [ 1.3342, -1.3869, -0.6273, -0.0880, -1.0567]],
       grad_fn=<EmbeddingBackward0>)